deployment: 
  namespace: test-lambda
  replicaCount: 1

  image:
    repository: 155244689895.dkr.ecr.ap-southeast-1.amazonaws.com/test-lambda/lambda-test
    tag: "24.08.26.7"
    pullPolicy: IfNotPresent

  serviceAccount:
    name: certificate-event-publisher
    automountServiceAccountToken: true

  resources:
    limits:
      memory: "128Mi"
      cpu: "500m"
    requests:
      memory: "64Mi"
      cpu: "250m"

  env:
    CERT_NAMESPACE: test-lambda
    CERT_NAMES: 
      - saml-cert-1
      - saml-cert-2
      - saml-cert-3
    CERT_SECRET_NAMES: 
      - saml-cert-tls-1
      - saml-cert-tls-2
      - saml-cert-tls-3
    AWS_REGION: ap-southeast-1
    EVENT_BUS_NAME: lambda-event
    EVENT_SOURCE: saml-cert
    EVENT_DETAIL_TYPE: CertificateChanged


serviceAccount:
  namespace: test-lambda
  name: certificate-event-publisher
  annotations:
    eksRoleArn: arn:aws:iam::155244689895:role/lambda-appstreamrole

rbac:
  namespace: test-lambda
  role:
    name: certificate-event-publisher

  roleBinding:
    name: certificate-event-publisher
