apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Values.rbac.role.name }}
  namespace: {{ .Values.rbac.namespace }}
rules:
  - apiGroups: [""]
    resources:
      - secrets
    verbs:
      - get
      - list
      - watch

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Values.rbac.roleBinding.name }}
  namespace: {{ .Values.rbac.namespace }}
subjects:
  - kind: ServiceAccount
    name: {{ .Values.serviceAccount.name }}
    namespace: {{ .Values.rbac.namespace }}
roleRef:
  kind: Role
  name: {{ .Values.rbac.role.name }}
  apiGroup: rbac.authorization.k8s.io
